/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nazar.pertemuan9.cobadatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alwi
 */
public class FormKoneksi extends javax.swing.JFrame {
    private static Connection koneksi;
    private DefaultTableModel model;
    /**
     * Creates new form FormKoneksi
     */
    public FormKoneksi() {
        initComponents();
        model = new DefaultTableModel();
        this.jTable1.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Alamat");
        model.addColumn("Telepon");
        ambilDataTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelepon = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbAdd = new javax.swing.JButton();
        cmbEdit = new javax.swing.JButton();
        cmbDelete = new javax.swing.JButton();
        cmbRefresh = new javax.swing.JButton();
        lblKode = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CRUD dengan Java NetBeans dan MySQL");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Telepon");

        txtTelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeleponActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(153, 153, 153));
        jTable1.setShowGrid(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        cmbAdd.setText("Add");
        cmbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAddActionPerformed(evt);
            }
        });

        cmbEdit.setText("Edit");
        cmbEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEditActionPerformed(evt);
            }
        });

        cmbDelete.setText("Delete");
        cmbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeleteActionPerformed(evt);
            }
        });

        cmbRefresh.setText("Refresh");
        cmbRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRefreshActionPerformed(evt);
            }
        });

        lblKode.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKode))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtAlamat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelepon))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbRefresh)))
                        .addGap(0, 79, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdd)
                    .addComponent(cmbEdit)
                    .addComponent(cmbDelete)
                    .addComponent(cmbRefresh))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTeleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeleponActionPerformed

    private void cmbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAddActionPerformed
        // TODO add your handling code here:
        Connection c = bukaKoneksi();
        
        if ("Add".equals(this.cmbAdd.getText())) {
            this.cmbAdd.setText("Save");
            this.cmbEdit.setText("Cancel");
            this.cmbDelete.enable(false);
            this.cmbRefresh.enable(false);
            this.lblKode.setText("0");
            this.txtNama.setText("");
            this.txtAlamat.setText("");
            this.txtTelepon.setText("");
        } else if ("Save".equals(this.cmbAdd.getText())) {
            String sqlKode = "Insert into anggota ('nama', 'alamat', 'tlp') " 
                    + "values ('" + this.txtNama.getText() + "',"
                    + "'" + this.txtAlamat.getText() + "',"
                    + "'" + this.txtTelepon.getText() + "')";
            
            try {
                PreparedStatement p2 = (PreparedStatement) c.prepareStatement(sqlKode);
                p2.executeUpdate();
                p2.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + ex.getMessage());
            }
            
            this.cmbAdd.setText("Add");
            this.cmbEdit.setText("Edit");
            this.cmbDelete.enable(true);
            this.cmbRefresh.enable(true);
        } else if ("Update".equals(this.cmbAdd.getText())) {
            String sqlKode = "Update anggota SET 'nama'='" + this.txtNama.getText() + "'," 
                    + " 'alamat'='" + this.txtAlamat.getText() + "' "
                    + "Where ID='" + this.lblKode.getText() + "'";
            
            try {
                PreparedStatement p2 = (PreparedStatement) c.prepareStatement(sqlKode);
                p2.executeUpdate();
                p2.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + ex.getMessage());
            }
            
            this.cmbAdd.setText("Add");
            this.cmbEdit.setText("Edit");
            this.cmbDelete.enable(true);
            this.cmbRefresh.enable(true);
        }
    }//GEN-LAST:event_cmbAddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        this.ambilTabelKlik();
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEditActionPerformed
        // TODO add your handling code here:
        if ("Edit".equals(this.cmbEdit.getText())) {
            this.cmbAdd.setText("Update");
            this.cmbEdit.setText("Cancel");
            this.cmbDelete.enable(false);
            this.cmbRefresh.enable(false);
        } else if ("Cancel".equals(this.cmbEdit.getText())) {
            this.cmbAdd.setText("Add");
            this.cmbEdit.setText("Edit");
            this.cmbDelete.enable(false);
            this.cmbRefresh.enable(false);
        }
    }//GEN-LAST:event_cmbEditActionPerformed

    private void cmbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeleteActionPerformed
        // TODO add your handling code here:
        Connection c = bukaKoneksi();
        String sqlKode = "Delete from anggota " + "Where ID='" + this.lblKode.getText() + "'";
        
        try {
            PreparedStatement p2 = (PreparedStatement) c.prepareStatement(sqlKode);
            p2.executeUpdate();
            p2.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan " + ex.getMessage());
        }
    }//GEN-LAST:event_cmbDeleteActionPerformed

    private void cmbRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRefreshActionPerformed
        // TODO add your handling code here:
        ambilDataTable();
    }//GEN-LAST:event_cmbRefreshActionPerformed

    private static Connection bukaKoneksi() {
        if (koneksi==null) {
            try {
                String url="jdbc:mysql://localhost:3306/belajar"; 
                String user="root";
                String password="";
                
                DriverManager.registerDriver(new com.mysql.jdbc.Driver()); 
                koneksi = DriverManager.getConnection(url,user,password);
            } catch (SQLException t) {
                System.out.println("Error membuat koneksi");
            } 
        }
        return koneksi;
    }
    
    private void ambilDataTable() {
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try {
            Connection c = bukaKoneksi();
            Statement s = c.createStatement();
            String sql = "Select * form anggota";
            ResultSet r = s.executeQuery(sql);
            
            while (r.next()) {
                Object[] o=new Object[4];
                o[0]=r.getString("id");
                o[1]=r.getString("nama");
                o[2]=r.getString("alamat");
                o[3]=r.getString("tlp");
                model.addRow(o);
            }
            r.close();
            s.close();
            ambilTabelKlik();
        }catch(SQLException e) {
            System.out.println("Terjadi kesalahan "+e.getMessage());
        }
    }
    
    private void ambilTabelKlik() {
        int i = this.jTable1.getSelectedRow(); 
        if(i==-1) {
            return;
        }
        String kode = (String) model.getValueAt(i, 0); 
        this.lblKode.setText(kode);
        String nama = (String) model.getValueAt(i, 0); 
        this.txtNama.setText(nama);
        String alamat = (String) model.getValueAt(i, 1); 
        this.txtAlamat.setText(alamat);
        String tlp = (String) model.getValueAt(i, 2); 
        this.txtTelepon.setText(tlp);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKoneksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKoneksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbAdd;
    private javax.swing.JButton cmbDelete;
    private javax.swing.JButton cmbEdit;
    private javax.swing.JButton cmbRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblKode;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
